import { algoliasearch } from 'algoliasearch';

// Algolia configuration
const ALGOLIA_APP_ID = '9U680JAGZW';
const ALGOLIA_SEARCH_API_KEY = '907f511c006316a5af872668ed7dde55';
const ALGOLIA_WRITE_API_KEY = 'bdaaee793d25f0dfa3a67ebf95a2efe1';

// Initialize Algolia clients
export const searchClient = algoliasearch(ALGOLIA_APP_ID, ALGOLIA_SEARCH_API_KEY);
export const writeClient = algoliasearch(ALGOLIA_APP_ID, ALGOLIA_WRITE_API_KEY);

// Index names
export const CANDIDATES_INDEX = 'candidates';
export const JOBS_INDEX = 'jobs';

// Candidate data transformation for Algolia
export function transformCandidateForAlgolia(candidate: any) {
  return {
    objectID: candidate.id,
    firstName: candidate.firstName,
    lastName: candidate.lastName,
    fullName: `${candidate.firstName || ''} ${candidate.lastName || ''}`.trim(),
    email: candidate.email,
    currentTitle: candidate.currentTitle,
    currentLocation: candidate.currentLocation,
    summary: candidate.summary,
    experienceYears: candidate.experienceYears,
    technicalSkills: candidate.technicalSkills || [],
    softSkills: candidate.softSkills || [],
    spokenLanguages: candidate.spokenLanguages || [],
    status: candidate.status,
    seniorityLevel: candidate.seniorityLevel,
    primaryIndustry: candidate.primaryIndustry,
    expectedSalary: candidate.expectedSalary,
    remotePreference: candidate.remotePreference,
    professionalHeadline: candidate.professionalHeadline,
    nationality: candidate.nationality,
    timezone: candidate.timezone,
    workPermitType: candidate.workPermitType,
    availableFrom: candidate.availableFrom,
    graduationYear: candidate.graduationYear,
    educationLevel: candidate.educationLevel,
    functionalDomain: candidate.functionalDomain,
    preferredContractType: candidate.preferredContractType,
    relocationWillingness: candidate.relocationWillingness,
    freelancer: candidate.freelancer,
    programmingLanguages: candidate.programmingLanguages || [],
    frameworks: candidate.frameworks || [],
    toolsAndPlatforms: candidate.toolsAndPlatforms || [],
    methodologies: candidate.methodologies || [],
    certifications: candidate.certifications || [],
    degrees: candidate.degrees || [],
    universities: candidate.universities || [],
    notableProjects: candidate.notableProjects || [],
    tags: candidate.tags || [],
    source: candidate.source,
    createdAt: candidate.createdAt,
    lastUpdated: candidate.lastUpdated,
    // Searchable text fields
    _searchableText: [
      candidate.firstName,
      candidate.lastName,
      candidate.email,
      candidate.currentTitle,
      candidate.currentLocation,
      candidate.summary,
      candidate.professionalHeadline,
      ...(candidate.technicalSkills || []),
      ...(candidate.softSkills || []),
      ...(candidate.spokenLanguages || []),
      ...(candidate.programmingLanguages || []),
      ...(candidate.frameworks || []),
      ...(candidate.toolsAndPlatforms || []),
      ...(candidate.methodologies || []),
      ...(candidate.certifications || []),
      ...(candidate.degrees || []),
      ...(candidate.universities || []),
      ...(candidate.tags || []),
    ].filter(Boolean).join(' '),
  };
}

// Job data transformation for Algolia
export function transformJobForAlgolia(job: any) {
  return {
    objectID: job.id,
    title: job.title,
    company: job.company,
    location: job.location,
    description: job.description,
    requirements: job.requirements,
    responsibilities: job.responsibilities,
    salaryRange: job.salaryRange,
    employmentType: job.employmentType,
    experienceLevel: job.experienceLevel,
    department: job.department,
    skills: job.skills || [],
    benefits: job.benefits || [],
    status: job.status,
    remote: job.remote,
    urgent: job.urgent,
    featured: job.featured,
    applicationDeadline: job.applicationDeadline,
    startDate: job.startDate,
    createdAt: job.createdAt,
    updatedAt: job.updatedAt,
    // Searchable text fields
    _searchableText: [
      job.title,
      job.company,
      job.location,
      job.description,
      job.requirements,
      job.responsibilities,
      job.department,
      ...(job.skills || []),
      ...(job.benefits || []),
    ].filter(Boolean).join(' '),
  };
}

// Algolia search configuration
export const candidateSearchConfig = {
  attributesToRetrieve: [
    'objectID',
    'firstName',
    'lastName',
    'fullName',
    'email',
    'currentTitle',
    'currentLocation',
    'summary',
    'experienceYears',
    'technicalSkills',
    'softSkills',
    'status',
    'seniorityLevel',
    'expectedSalary',
    'createdAt',
  ],
  searchableAttributes: [
    'fullName',
    'firstName',
    'lastName',
    'email',
    'currentTitle',
    'currentLocation',
    'summary',
    'professionalHeadline',
    'technicalSkills',
    'softSkills',
    'spokenLanguages',
    'programmingLanguages',
    'frameworks',
    'toolsAndPlatforms',
    'methodologies',
    'certifications',
    'degrees',
    'universities',
    'tags',
    '_searchableText',
  ],
  attributesForFaceting: [
    'status',
    'seniorityLevel',
    'primaryIndustry',
    'remotePreference',
    'educationLevel',
    'functionalDomain',
    'preferredContractType',
    'nationality',
    'workPermitType',
    'technicalSkills',
    'programmingLanguages',
    'frameworks',
    'source',
  ],
  ranking: [
    'typo',
    'geo',
    'words',
    'filters',
    'proximity',
    'attribute',
    'exact',
    'custom',
  ],
  customRanking: [
    'desc(experienceYears)',
    'desc(createdAt)',
  ],
};

export const jobSearchConfig = {
  attributesToRetrieve: [
    'objectID',
    'title',
    'company',
    'location',
    'description',
    'requirements',
    'responsibilities',
    'salaryRange',
    'employmentType',
    'experienceLevel',
    'department',
    'skills',
    'status',
    'remote',
    'urgent',
    'featured',
    'createdAt',
  ],
  searchableAttributes: [
    'title',
    'company',
    'location',
    'description',
    'requirements',
    'responsibilities',
    'department',
    'skills',
    'benefits',
    '_searchableText',
  ],
  attributesForFaceting: [
    'status',
    'employmentType',
    'experienceLevel',
    'department',
    'remote',
    'urgent',
    'featured',
    'skills',
    'company',
    'location',
  ],
  ranking: [
    'typo',
    'geo',
    'words',
    'filters',
    'proximity',
    'attribute',
    'exact',
    'custom',
  ],
  customRanking: [
    'desc(featured)',
    'desc(urgent)',
    'desc(createdAt)',
  ],
};
